language: node_js
sudo: required

node_js:
- "node"

services:
- docker

env:
  global:
    - NODE_TLS_REJECT_UNAUTHORIZED=0
    - BOILERPLATE_DOMAIN=boilerplate.local
    - BOILERPLATE_IPV4_16PREFIX=172.16
    - BOILERPLATE_IPV6_SUBNET=bade:affe:dead:beef:b011::/80
    - BOILERPLATE_IPV6_ADDRESS=bade:affe:dead:beef:b011:0642:ac10:0080
    - BOILERPLATE_WWW_CERTS=./certs
    - BOILERPLATE_API_SECRETKEY=hBDwM7CnSd2vYHtphzaewTvw
    - BOILERPLATE_DB_PASSWORD=FsehrxcVFr7mWeFxvhr9UWvn

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build www
  - sleep 20  # waiting for the database to come up

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build test-e2e
  - exit $(docker-compose -f docker-compose.yml -f docker-compose.test.yml ps -q | xargs docker inspect -f '{{ .State.ExitCode }}' | grep -v 0 | wc -l | tr -d ' ')
